name: PHP Linting

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4]
    steps:
    - uses: actions/checkout@v2

    - name: PHP Version
      run: php --version

    - name: Lint PHP Files
      run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

    - name: Lint PHP Files ( 8 threads )
      run: find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

#    - name: Cache composer dependencies
#      uses: actions/cache@v1
#      with:
#        path: vendor
#        key: composer-${{ hashFiles('composer.lock') }}

    - name: test exists
      if: ${{hashFiles('composer.json')}}
      run: echo "composer.json exists"

    - name: test does not exists
      if: ${{hashFiles('banana.json')}}
      run: echo "banana.json exists"

    - name: Validate composer.json and composer.lock
      run: ls composer.json > /dev/null && composer validate

    - name: Composer Install
      run: ls composer.json > /dev/null && composer install

    - name: Run PHPUnit tests
      run: ls vendor/bin/phpunit > /dev/null && ./vendor/bin/phpunit
